source "https://rubygems.org"

gemspec

gem "sidekiq"

gem "rspec", "~> 3.11"
gem "sqlite3", require: false

# Exclude development-only gems from the gemfiles generated by appraisal.
unless defined?(::Appraisal::Gemfile) && is_a?(::Appraisal::Gemfile)
  group :development do
    gem "appraisal"
    gem "standard", "~>1.0"
    gem "simplecov", "~>1.0", require: false
    gem "yard"
  end
end
