name: Continuous Integration
on:
  push:
    branches:
      - master
      - actions-*
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  BUNDLE_CLEAN: "true"
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
jobs:
  specs:
    name: Run specs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "ruby"
            standardrb: true
          - ruby: "3.4"
            appraisal: "activerecord_8.1"
          - ruby: "3.3"
            appraisal: "activerecord_8.0"
          - ruby: "3.3"
            appraisal: "activerecord_7.2"
          - ruby: "3.2"
            appraisal: "activerecord_7.1"
          - ruby: "3.2"
            appraisal: "activerecord_7.0"
          - ruby: "3.1"
            appraisal: "activerecord_6.1"
          - ruby: "3.0"
            appraisal: "activerecord_6.0"
          - ruby: "2.7"
            appraisal: "activerecord_5.2"
          - ruby: "2.5"
            appraisal: "activerecord_5.1"
          - ruby: "ruby"
            appraisal: "without_sidekiq"
          - ruby: "3.4"
            appraisal: "sidekiq_8"
          - ruby: "3.2"
            appraisal: "sidekiq_7"
          - ruby: "3.0"
            appraisal: "sidekiq_6"
          - ruby: "2.7"
            appraisal: "sidekiq_5"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
      - name: Set Appraisal bundle
        if: matrix.appraisal != ''
        run: |
          echo "using gemfile gemfiles/${{ matrix.appraisal }}.gemfile"
          bundle config set gemfile "gemfiles/${{ matrix.appraisal }}.gemfile"
      - name: Install bundler
        run: |
          bundle update
      - name: Run specs
        run: |
          bundle exec rake spec
      - name: Run standardrb
        if:   matrix.standardrb == true
        run:  bundle exec rake standard
